FROM cartesi/image-ci

MAINTAINER Carlo Fragni <carlo@cartesi.io>

ENV BASE=/opt/core-manager
ENV EMU_BASE=$BASE/core/src/emulator

RUN mkdir $BASE

COPY requirements.txt $BASE/

# Install python and other dependencies
RUN \
    apt-get update && \
    apt-get install -y python3 python3-pip

RUN \
    pip3 install -r $BASE/requirements.txt

COPY . $BASE

#Building the emulator
RUN \
    cd $EMU_BASE && \
    make clean && \
    make grpc

#Making grpc/protobuf autogenerated python code files
RUN \
    cd $BASE/core/cartesi-grpc && \
    bash generate_python_grpc_code.sh

#Changing directory to base
WORKDIR $BASE
CMD python3 manager_server.py -a 0.0.0.0
