#!/bin/sh

set -e

mkdir -p test-files
#wget -O test-files/linux.bin -c https://github.com/cartesi/image-kernel/releases/download/v0.7.0/linux-5.5.19-ctsi-2.bin
#wget -O test-files/rom.bin -c https://github.com/cartesi/machine-emulator-rom/releases/download/v0.4.0/rom.bin
#wget -O test-files/rootfs.ext2 -c https://github.com/cartesi/image-rootfs/releases/download/v0.6.0/rootfs.ext2

SCRIPTPATH="$( cd "$(dirname "$0")" ; pwd -P )"
MANAGER_DIR=${MANAGER_PATH:-${SCRIPTPATH}}
export PYTHONPATH=${MANAGER_DIR}/proto

python3 test_client.py $@
