name: Docker
on: [push]
env:
  ROM_VERSION: v0.8.0
  KERNEL_VERSION: v0.9.0
  ROOTFS_VERSION: v0.8.0
  EMULATOR_VERSION: 0.8.0
  KERNEL_FILE: linux-5.5.19-ctsi-3.bin
jobs:
  build:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2
        with:
          submodules: recursive
          token: ${{ secrets.CI_TOKEN }}

      - name: Install dependencies
        run: |
          sudo apt-get update -y
          sudo apt-get install -y build-essential curl libboost-filesystem-dev libreadline-dev libboost-context-dev libboost-coroutine-dev libboost-serialization-dev libboost-filesystem-dev libssl-dev libc-ares-dev zlib1g-dev ca-certificates patchelf automake cmake liblua5.3-dev lua-socket
          pip3 install -r requirements.txt
          curl https://sh.rustup.rs -sSf | bash -s -- -y
          echo 'source $HOME/.cargo/env' >> $HOME/.bashrc

      - name: Download [machine-emulator]
        uses: Legion2/download-release-action@v2.1.0
        with:
          repository: ${{ github.repository_owner }}/machine-emulator
          tag: v${{ env.EMULATOR_VERSION }}
          file: machine-emulator-Linux-v${{ env.EMULATOR_VERSION }}.tar.gz
          token: ${{ secrets.CI_TOKEN }}

      - name: Download [rootfs.ext2]
        uses: Legion2/download-release-action@v2.1.0
        with:
          repository: ${{ github.repository_owner }}/image-rootfs
          tag: ${{ env.ROOTFS_VERSION }}
          file: rootfs.ext2
          token: ${{ secrets.CI_TOKEN }}

      - name: Download [kernel.bin]
        uses: Legion2/download-release-action@v2.1.0
        with:
          repository: ${{ github.repository_owner }}/image-kernel
          tag: ${{ env.KERNEL_VERSION }}
          file: ${{ env.KERNEL_FILE }}
          token: ${{ secrets.CI_TOKEN }}

      - name: Download [rom.bin]
        uses: Legion2/download-release-action@v2.1.0
        with:
          repository: ${{ github.repository_owner }}/machine-emulator-rom
          tag: ${{ env.ROM_VERSION }}
          file: rom.bin
          token: ${{ secrets.CI_TOKEN }}

      - name: Install emulator and images to /opt/cartesi directory
        run: |
          mkdir -p /opt/cartesi/share/images
          tar -xzf machine-emulator-Linux-v${{ env.EMULATOR_VERSION }}.tar.gz -C /opt/cartesi
          mv rom.bin rootfs.ext2 ${{env.KERNEL_FILE}} /opt/cartesi/share/images
          ln -s /opt/cartesi/share/images/${{ env.KERNEL_FILE }} /opt/cartesi/share/images/linux.bin

      - name: Generate grpc python code
        run: |
          ./generate-cartesi-gprc

      - name: Install machine manager
        run: |
          ./install.sh

      - name: Execute Machine Manager Tests
        run: |
          export CARTESI_BIN_PATH=/opt/cartesi/bin
          export CARTESI_IMAGE_PATH=/opt/cartesi/share/images
          cd tests/rust-test-client && cargo test --release

  build-docker-image:
    runs-on: ubuntu-20.04
    needs: [build]
    steps:
      - uses: actions/checkout@v2
        with:
          submodules: recursive
          token: ${{ secrets.CI_TOKEN }}

      - name: Set up Docker Buildx
        id: buildx
        uses: docker/setup-buildx-action@v1

      - name: Cache Docker layers
        uses: actions/cache@v2
        with:
          path: /tmp/.ubuntu-buildx-cache
          key: ${{ runner.os }}-ubuntu-buildx-${{ github.sha }}
          restore-keys: |
            ${{ runner.os }}-ubuntu-buildx-

      - name: Login to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Setup docker image tags
        id: docker_image_tags
        uses: docker/metadata-action@v3
        with:
          images: ${{ secrets.DOCKER_ORGANIZATION }}/machine-manager
          tags: |
            type=ref,event=branch
            type=semver,pattern={{version}}

      - name: Set test image tag name
        id: docker_test_image_tag
        run: echo ::set-output name=name::$(echo "${{ steps.docker_image_tags.outputs.tags }}" | head -n 1 | xargs)

      - name: Build test docker image
        id: docker_build_test
        uses: docker/build-push-action@v2
        with:
          builder: ${{ steps.buildx.outputs.name }}
          context: .
          push: false
          load: true
          tags: ${{ steps.docker_test_image_tag.outputs.name }}
          cache-from: type=local,src=/tmp/.ubuntu-buildx-cache
          cache-to: type=local,dest=/tmp/.ubuntu-buildx-cache
          build-args: |
            EMULATOR_REPOSITORY=${{ secrets.DOCKER_ORGANIZATION }}/machine-emulator
            EMULATOR_VERSION=${{ env.EMULATOR_VERSION }}

      - name: Test docker image
        run: |
          docker pull fullstorydev/grpcurl:v1.8.5
          docker run --network=host --name cartesi_mm_container -t ${{ steps.docker_test_image_tag.outputs.name }} &
          timeout 20 bash -c 'while ! nc -q0 127.0.0.1 50051 < /dev/null > /dev/null 2>&1; do sleep 1; done'
          docker run --network=host fullstorydev/grpcurl -plaintext 127.0.0.1:50051 list
          docker kill cartesi_mm_container

      - name: Build and push docker image
        if: ${{ startsWith(github.ref, 'refs/tags/v') || (github.ref == 'refs/heads/develop') }}
        id: docker_build
        uses: docker/build-push-action@v2
        with:
          builder: ${{ steps.buildx.outputs.name }}
          context: .
          push: true
          load: false
          tags: ${{ steps.docker_image_tags.outputs.tags }}
          cache-from: type=local,src=/tmp/.ubuntu-buildx-cache
          cache-to: type=local,dest=/tmp/.ubuntu-buildx-cache
          build-args: |
            EMULATOR_REPOSITORY=${{ secrets.DOCKER_ORGANIZATION }}/machine-emulator
            EMULATOR_VERSION=${{ env.EMULATOR_VERSION }}
